name: SmartActors
title: SmartTools - Tutorials
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/tutorials"
url: "https://smarttools.github.io"
github_username:  SmartTools
encoding: utf-8

VERSION: 0.3.3

ASSET_PATH: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: /:categories/:year/:month/:day/:title
highlighter: rouge
gems:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
