title: SmartTools - Tutorials
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/tutorials"
url: "https://http://smarttools.github.io"
github_username:  SmartTools
encoding: utf-8

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
theme: minima
permalink: pretty
highlighter: rouge
gems:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
