name: SmartActors
title: SmartTools - Tutorials
description: > # this means to ignore newlines until "baseurl:"
  Here are some examples and tutorials how to use SmartActors library.
baseurl: "/tutorials"
url: "https://smarttools.github.io"
github_username:  SmartTools
encoding: utf-8

VERSION: 0.5.0

ASSET_PATH: false

# Build settings
markdown_ext: "md"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: /:categories/:year/:month/:day/:title
highlighter: rouge
gems:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

keep_files:
  - src/
