title: SmartTools - Tutorials
email: tutorials@smart-tools.info
description: > # this means to ignore newlines until "baseurl:"
  Here are some examples and tutorials how to use SmartActors library.
baseurl: "/tutorials"
url: "https://http://smarttools.github.io"
github_username:  SmartTools
encoding: utf-8

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
theme: minima
permalink: pretty
highlighter: rouge
gems:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
